// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2020-03-02 05:45:02

package com.aliyun.mpaas.demo.android60.launcher.model;


public class User {
    public String name;
    public Integer age;

}