// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2020-03-01 19:58:19

package com.aliyun.mpaas.demo.android60.launcher.request;

import com.aliyun.mpaas.demo.android60.launcher.model.User;

public class PathMpaasMgsHttpPostFormPostReq {
    public User _requestBody;

}