// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2020-02-29 20:11:36

package com.aliyun.mpaas.demo.android60.launcher.request;


public class PathMpaasMgsHttpGetQuerystrGetReq {
    public String querystring1;

}