// Generated by HybirdPB CodeGenerator(1.2.0). DO NOT EDIT!
// Generation date is 2020-03-01 06:25:36

package com.aliyun.mpaas.demo.android60.launcher.request;


public class PathMpaasMgsHttpDeleteIdDeleteReq {
    public String id;

}